LOCAL_PATH := $(my-dir)

ifeq ($(DEVICE_TYPE), mmc)
include $(CLEAR_VARS)
CMAKE_PATH=$(LOCAL_PATH)/getpackage
LOCAL_MODULE:=getpackage
CMAKE_CONF_OPTS:=-DMMC_INDEX=$(TARGET_BOARD_MSC_INDEX)
LOCAL_MODULE_TAGS :=optional
include $(BUILD_CMAKE_DEVICE)

include $(CLEAR_VARS)
CMAKE_PATH=$(LOCAL_PATH)/libupdater
LOCAL_MODULE:=libupdater
CMAKE_CONF_OPTS:=-DBUILD_MMC_DEVICE=ON
LOCAL_MODULE_TAGS :=optional
include $(BUILD_CMAKE_DEVICE)

include $(CLEAR_VARS)
CMAKE_PATH=$(LOCAL_PATH)/recovery
LOCAL_MODULE:=recovery
CMAKE_CONF_OPTS:=-DBUILD_MMC_DEVICE=ON
CMAKE_CONF_OPTS+=-DRECOVERY_CONF_PATH=$(DEVICE_PATH)/ota-overlay/package_config
CMAKE_CONF_OPTS+=-DPARTITION_MMC_CONF_PATH=$(DEVICE_PATH)/ota-overlay/package_config
CMAKE_CONF_OPTS+=-DMMC_INDEX=$(TARGET_BOARD_MSC_INDEX)
LOCAL_MODULE_TAGS :=optional
include $(BUILD_CMAKE_DEVICE)
else
include $(CLEAR_VARS)
CMAKE_PATH=$(LOCAL_PATH)/libupdater
LOCAL_MODULE:=libupdater
LOCAL_MODULE_TAGS :=optional
include $(BUILD_CMAKE_DEVICE)

include $(CLEAR_VARS)
CMAKE_PATH=$(LOCAL_PATH)/recovery
LOCAL_MODULE:=recovery
ifeq ($(strip $(TARGET_EXT_SUPPORT)),5.10)
CMAKE_CONF_OPTS:=-DKERNEL_5_10=ON
endif
CMAKE_CONF_OPTS+=-DRECOVERY_CONF_PATH=$(DEVICE_PATH)/ota-overlay/package_config
LOCAL_MODULE_TAGS :=optional
include $(BUILD_CMAKE_DEVICE)

include $(CLEAR_VARS)
CMAKE_PATH=$(LOCAL_PATH)/recovery
LOCAL_MODULE:=recovery_static_lib
ifeq ($(strip $(TARGET_EXT_SUPPORT)),5.10)
CMAKE_CONF_OPTS:=-DKERNEL_5_10=ON -DNV_USE_STATIC_LIB=ON
endif
LOCAL_MODULE_TAGS :=optional
include $(BUILD_CMAKE_DEVICE)
endif
