#!/bin/sh

case "$1" in
	start)
        echo "set update env ..."
        echo "start update..."
		/usr/data/ota_res/update.sh &
        ;;
	stop)
        ;;
	restart|reload)
        ;;
	*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?




