LOCAL_PATH := $(my-dir)

include $(CLEAR_VARS)
CMAKE_PATH=$(LOCAL_PATH)
LOCAL_MODULE:= stereo-demo
LOCAL_MODULE_TAGS :=optional
CMAKE_CONF_OPTS := -DMSA_ENABLE=ON -DOPENCV_ENABLE=ON
include $(BUILD_CMAKE_DEVICE)
