
#INCLUDE_DIRECTORIES(	${PROJECT_SOURCE_DIR}
#	${PROJECT_SOURCE_DIR}/third_party/include/SDL2
#)

SET(APP_FILES
	${PROJECT_SOURCE_DIR}/app/ffplay-client.c
)



add_executable(ffplayer ${APP_FILES})
TARGET_LINK_LIBRARIES(ffplayer ffplay)

install(FILES ${CMAKE_BINARY_DIR}/app/ffplayer DESTINATION /usr/bin PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)

