LOCAL_PATH := $(my-dir)
include $(CLEAR_VARS)
CMAKE_PATH=$(LOCAL_PATH)
LOCAL_MODULE:= ingenic-systemServer
LOCAL_MODULE_TAGS :=optional
LOCAL_DEPANNER_MODULES:=ingenic-mpp
CMAKE_CONF_OPTS := -DCHIP_PLATFORM=$(TARGET_BOARD_PLATFORM)
include $(BUILD_CMAKE_DEVICE)

