LOCAL_PATH := $(my-dir)
include $(CLEAR_VARS)
CMAKE_PATH=$(LOCAL_PATH)
LOCAL_MODULE:= LVGL_DEMO_WIDGETS
LOCAL_MODULE_TAGS :=optional
LOCAL_DEPANNER_MODULES := raw_lvgl raw_lvgldrv
include $(BUILD_CMAKE_DEVICE)
