pcm.!default
{
   type asym
    playback.pcm "play_chn0"
    capture.pcm "cap_chn0"
}

pcm.convert_play_chn0 {
	type plug
	slave {
		pcm dmixer
	}
}

pcm.play_chn1 {
	type plug
	slave {
		pcm dmixer
	}
}

pcm.convert_cap_chn0 {
    type plug
    slave {
        pcm dsnooper
    }
}

pcm.cap_dmic {
    type plug
    slave {
        pcm "hw:0,5"
    	channels 2
	rate 16000
   }
}

pcm.dmixer  {
    type dmix
    ipc_key 772357
    ipc_key_add_uid yes
    slave {
	    pcm "hw:0,0"
	    period_time 0
	    period_size 320
	    buffer_size 2560
	    rate 16000
	}
}

pcm.dsnooper {
    type dsnoop
    ipc_key 772358
    ipc_key_add_uid yes
    slave {
        pcm "hw:0,6"
	period_time 0
        channels 2
	period_size 320
	buffer_size 2560
        rate 16000
    }
    bindings {
     0 0
     1 1
    }
}


ctl.dmixer {
     type hw
     card 0
}

ctl.dsnooper {
     type hw
     card 0
}

pcm.play_chn0 {
	type softvol
	slave {
		pcm convert_play_chn0
	}

	control {
		name "chan0 play volume"
	}

	min_dB -40.0
	max_dB 10.0
	resolution 50
}

pcm.cap_chn0 {
	type softvol
	slave {
		pcm convert_cap_chn0
	}

	control {
		name "chan0 cap volume"
	}

	min_dB -40.0
	max_dB 10.0
	resolution 50
}
