#!/bin/sh

# mount filesystems
/bin/mount -t tmpfs tmpfs /dev
/bin/mkdir -p /dev/pts /dev/shm
mknod /dev/zero c 1 5
mknod /dev/loop0 b 7 0
mknod /dev/loop1 b 7 1
mknod /dev/loop2 b 7 2

/bin/mknod /dev/console c 5 1
/bin/mknod /dev/null c 1 3
/bin/mount -a


# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
#source /etc/profile
echo "Starting rcS..."
for i in /etc/init.d/S??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i start
	    ;;
    esac
done
/usr/bin/fbshow /logo.jpg /dev/fb0
