#!/bin/sh
case "$1" in
	start)
		echo "Storage Init..."
		echo "mount mmcblk0p9..."
		while [ ! -b /dev/mmcblk0p9 ];do
			echo "wait /dev/mmcblk0p9..."
			wait
		done
		if [ ! -d "/storage" ]; then
			mkdir -p /storage
		fi
		/bin/umount /storage
		#checkfs
		/bin/mount -t ext4 -o defaults,noatime,nodiratime,nobarrier,discard /dev/mmcblk0p9 /storage
		if [ $? -ne 0 ]
		then
			echo "mke2fs -t ext4 /dev/mmcblk0p9"
			/sbin/mke2fs /dev/mmcblk0p9
			/bin/mount -t ext4 -o defaults,noatime,nodiratime,nobarrier,discard /dev/mmcblk0p9 /storage
		fi
		;;
	stop)
		/bin/umount /storage
		;;
	restart|reload)
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		;;
esac

exit $?
