[update]
mediumtype=mmc
imgcnt=3
[image1]
name=kernel_recovery
type=normal
offset=0xc00000
bootmode=normal
updatemode=slice
[image2]
name=kernel
type=normal
offset=0x300000
bootmode=recovery
updatemode=slice
[image3]
name=system.ext2
type=normal
offset=0x19c00000
bootmode=recovery
updatemode=slice
